services:
  # Frontend Service (Static Site)
  - type: static
    name: hubisko-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    # Custom headers for SPA routing
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service  
  - type: web
    name: hubisko-api
    env: node
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: MONGODB_URI
    #   fromDatabase:
    #     name: your-database-name
    #     property: connectionString
